### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by Toyz** [inkyblackness/imgui-go#1]
How do I use a custom font with with lib using glfw as I am still pretty new to glfw in golang

**Comment by dertseha** [comment]
Hello there, @Toyz , thank you for your message!
At the moment, this wrapper does not support using custom fonts, the wrapper is still in-process of being extended. My main driver for extensions currently is the use within InkyBlackness.

However, I am considering to add custom font support soon, as I'm struggling with scaling the default font for HiDPI monitors (it looks bad). So I do have a need for custom fonts myself :)

For now I can't help you with this library as the function is not yet exposed. If you can wait a few days (weeks), I might add the function and come back to you with an example.
Is this OK for you?

**Comment by Toyz** [comment]
I can wait that’s not a problem at all I’m using this mainly for a private project to test my api

On Wed, Jun 20, 2018 at 10:06 AM Christian Haas <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello there, @Toyz<https://github.com/Toyz> , thank you for your message!
At the moment, this wrapper does not support using custom fonts, the wrapper is still in-process of being extended. My main driver for extensions currently is the use within InkyBlackness.

However, I am considering to add custom font support soon, as I'm struggling with scaling the default font for HiDPI monitors (it looks bad). So I do have a need for custom fonts myself :)

For now I can't help you with this library as the function is not yet exposed. If you can wait a few days (weeks), I might add the function and come back to you with an example.
Is this OK for you?

**Comment by dertseha** [comment]
Hello again!
The API has been minimally extended to allow adding custom font files to the FontAtlas.
So, before generating the font texture, call FontAtlas.AddFontFromFileTTF() .
For now this is the minimal API also available via ImGui - so far I opted out to include all special parameters :)

The first added font is the default one, others can be activated with imgui.PushFont(font) / imgui.PushFont() .

Have fun with it!
