### ISSUE TITLE
Refactoring coordination

### ISSUE THREAD

**Issue by neclepsio** [inkyblackness/imgui-go#103]
I completed my refactoring, moving C files in a separate folder, updating upstream to 1.76. I divided imgui.go in several files. It's in the refactor-1 branch of my fork. I'm going to implement the cleaning you you did while merging #97, then I'd open a pull request. It's pretty invasive so I think a little bit of coordination is needed to keep in sync. Are you planning other modifications, or should I pull my refactoring now?

**Comment by dertseha** [comment]
Thank you for the effort!
There are still a few issues open (there also have been a few changes after merging #97 / #102 ) - and I guess there will always be a few changes pending here and there :)
At best simply start the pull request and we can go from there.

**Comment by dertseha** [comment]
Addendum: Note that I'll probably do a release before working on this refactoring - otherwise it would be too many changes in one go.

**Comment by neclepsio** [comment]
Ok, I synced with your modifications of today and created the pull request.
