### ISSUE TITLE
android/arm build failure using gomobile

### ISSUE THREAD

**Issue by TheMightyGit** [inkyblackness/imgui-go#113]
imgui-go version: v2.4.0
host os: macos 10.15.4
target: android/arm
golang version: go version go1.14.3 darwin/amd64 (via brew)
gomobile version: gomobile version +4c31acb Sun Mar 29 12:56:38 2020 +0000 (android); androidSDK=
android-ndk: 21

```
gomobile build -target=android/arm ./cmd/rogueliz
gomobile: go build -buildmode=c-shared -o /var/folders/bg/nsdt68_n3dj_cznhv6jb2wf00000gn/T/gomobile-work-444068505/lib/armeabi-v7a/librogueliz.so rogueliz/cmd/rogueliz failed: exit status 2
# github.com/inkyblackness/imgui-go/v2
warning: unknown warning option '-Wno-subobject-linkage' [-Wunknown-warning-option]
# github.com/inkyblackness/imgui-go/v2
../go/pkg/mod/github.com/inkyblackness/imgui-go/v2@v2.4.0/AllocatedGlyphRanges.go:34:16: type [1073741824]uint16 too large
../go/pkg/mod/github.com/inkyblackness/imgui-go/v2@v2.4.0/GlyphRanges.go:24:16: type [1073741824]uint16 too large
```

android/arm64 builds fine, so it looks like something is overflowing 32 bits (?) but I'm not familiar enough with the imgui-go code to know what it's doing at these points to offer a fix.

**Comment by dertseha** [comment]
Hello there and thank you for the report!

This is a clone of #84 - yet thanks to more evidences I looked into it some more - and found the reason.
Await `v2.4.1` momentarily.
