### ISSUE TITLE
Light and Classic styles

### ISSUE THREAD

**Issue by quillaja** [inkyblackness/imgui-go#115]
I'm curious if you'd be interested in adding ports of the functions to set the "light" and "classic" styles that the C++ library offers? It looks like it would be pretty simple to create 2 funcs to match, something like `StyleColorsLight(Style)` and `StyleColorsClassic(Style)`, and then use the color values from the C++ source to set all the appropriate style ids.

I'd be happy to write those and submit a pull request if you'd like to add it to your port.

By the way, thank you so much for porting the excellent Imgui library to Go. It is an oasis in a desert of quality gui packages in Go.

**Comment by dertseha** [comment]
Hello there and thank you for your message!
It would be great if you add the functions, it would only be a few lines each.

Note: This is a wrapper, not a port, so almost anything calls the original C++ functions.

**Comment by quillaja** [comment]
I must have been looking at the older v1 docs, because those functions are already present in v2 in style.go lines 127 and 132.
