### ISSUE TITLE
Breaking Changes in 0feeb7fcffbf1163271bbaf1096839cb73653b05

### ISSUE THREAD

**Issue by JetSetIlly** [inkyblackness/imgui-go#140]
The recent merge has breaking changes. 0feeb7fcffbf1163271bbaf1096839cb73653b05

There might be others but the one I've bumped into straight away is the Slider flags being renamed

For example, imgui.SlidersFlagsNone is now imgui.SliderFlagNone

**Comment by dertseha** [comment]
That is correct. This is based on the most recent merge for the upgrade to 1.81 of **Dear ImGui** . Several things have changed and it will end up being a bump to major version 4.0.0 . If you need to stay on 3, you need to bind yourself on the `3.1.0` version.

**Comment by JetSetIlly** [comment]
Okay. Not a problem.
