### ISSUE TITLE
Add image rotation or show example of using AddImageV

### ISSUE THREAD

**Issue by VityaSchel** [inkyblackness/imgui-go#181]
Hello, I tried using image widgets but there is no rotation attribute. Also I couldn't find out what is AddImageV and how it works. From imgui, it seems that AddImage is alias for AddImageV with Vec2{0,0} and Vec2{1,1} 

https://github.com/inkyblackness/imgui-go/blob/dea92bb7231cf3441e30b373be87e2655b38a113/DrawList.go#L276
https://github.com/inkyblackness/imgui-go/blob/dea92bb7231cf3441e30b373be87e2655b38a113/DrawList.go#L277

But what is `col` variable with color? Why by default it's white and what's "packed" means?

Why AddImage works but AddImageV not? All I'm getting is filled monocolor rectangle and not distorted image that could be used for rotation.

**Comment by VityaSchel** [comment]
Ok it looks like it's impossible to rotate image with AddImageV and this method intended to distort image's [UV](https://en.wikipedia.org/wiki/UV_mapping). I thought of something like this:

![image](https://user-images.githubusercontent.com/59040542/173251512-5371d1a1-c239-4bf3-be4e-3c72ac759140.png)

so it would be easy to adjust these coordinates to (x, y, width, height, rotation)

**Comment by VityaSchel** [comment]
For anyone coming here in the future, AddImageV is basically how many times to repeat image inside (p1, p2) rectangle:

```go
canvas.AddImage(texture, p1, p2)
```

is the same as

```go
canvas.AddImageV(texture, p1, p2, image.Pt(10, 15), image.Pt(20, 20), color.RGBA{R: 255, G: 255, B: 255, A: 255})
```

except in second case, it repeats image 10 times horizontally and 5 times vertically making it a grid from 50 images inside that rectange :/

perhaps I should try opengl

**Comment by VityaSchel** [comment]
I tried solution descibed here

https://github.com/ocornut/imgui/issues/497#issuecomment-173369690

But I can't find PushTextureID, PrimReserve and PopTextureID methods. I'm using giu library for Go, so maybe move issue there?

**Comment by VityaSchel** [comment]
Somehow I missed AddImageQuad method in imgui, which does exactly what I need: distorting image by moving polygons. It's not added to imgui-go, so I created #118

**Comment by dertseha** [comment]
Thank you for the details. Closing in favor of the other task.
