### ISSUE TITLE
Add Image::AddImageQuad method 

### ISSUE THREAD

**Issue by VityaSchel** [inkyblackness/imgui-go#182]
Add AddImageQuad method implemented in
 https://github.com/inkyblackness/imgui-go/blob/44567f2af289573078d51719638e9b71c203e60e/imgui/imgui_draw.cpp#L1621 

to Go wrapper

**Comment by VityaSchel** [comment]
I'm not much into Go and learning it for about a week, so please correct me, if I'm wrong, but it seems, to resolve this, we only need to make several small modifications to files:

1. Add iggAddImageQuad method to wrapper/DrawList.cpp with call to 
```go
list->AddImageQuad(/*args*/)
```

2. Export it in wrapper/DrawList.h

3. Expose it in DrawList.go for imgui-go users by adding AddImageQuad func

Then, ask giu contributors to wrap it once more within giu. Or use imgui-go drawlist directly with giu helper.

**Comment by dertseha** [comment]
Hi there, and thank you for the proposal. The proposed path sounds right and it would be a good first issue to try out locally as well!

**Comment by VityaSchel** [comment]
> Hi there, and thank you for the proposal. The proposed path sounds right and it would be a good first issue to try out locally as well!

@dertseha I made a pull request (#185). Please tell me you can accept it! I tried my best to follow code style

**Comment by dertseha** [comment]
Done via #185 and #190 .
Thank you!
