### ISSUE TITLE
about window drag

### ISSUE THREAD

**Issue by caitou2019** [inkyblackness/imgui-go#183]
I see that other people's windows can be moved out of the main window. What do I need to do to achieve this? I can't move the sub window beyond the main window at present. Thank you very much!

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/47804016/175855336-488da3f0-9962-47cf-a3d4-d07bef474fc3.png">

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/47804016/175855431-4d89c770-c4b7-4d56-9509-e3da75002487.png">

**Comment by dertseha** [comment]
Hi there and thank you for your message.
This functionality is based on a yet unreleased branch that **imgui-go** doesn't support. There are other forks and experiments that cover this.
Please read up more about this in #112 .
