### ISSUE TITLE
GitHub Actions tests fail for Windows

### ISSUE THREAD

**Issue by neclepsio** [inkyblackness/imgui-go#184]
This is due to https://github.com/golang/go/issues/46099.

It can be fixed using older MinGW version.

**Comment by dertseha** [comment]
Thank you for the notice.
Marking this free for anyone.

**Comment by neclepsio** [comment]
Updating test for using Go 1.19 may solve this.

**Comment by dertseha** [comment]
I've removed the Windows build for now. I don't have the time for this, so it stays disabled to avoid blocking other PRs.

**Comment by dertseha** [comment]
Action remained disabled for Windows at time of archiving. Closing issue.
