### ISSUE TITLE
Disable assert in imgui

### ISSUE THREAD

**Issue by SuperLiveYou** [inkyblackness/imgui-go#188]
imgui.h Assertion im of line 1752 in  IM_ASSERT(Size > 0); It will prevent me from using PushColorWindowBg. Once I disable assertions, there will be no problems and no other problems. I don't understand the meaning of this paragraph

**Comment by SuperLiveYou** [comment]
![image](https://user-images.githubusercontent.com/68497295/185765123-2dec2ca0-2318-4802-8e38-51b2f64e155e.png)
![image](https://user-images.githubusercontent.com/68497295/185765131-ddbd0b4d-a93e-47e9-b4f6-38d9ba3d354e.png)

**Comment by SuperLiveYou** [comment]
My go version is 1.18

**Comment by dertseha** [comment]
Hello there, and thank you for your patience.
This particular assert ensures that `back()` is only called when there is at least one element in the `Data` array. If it is empty, the `Size` member will most likely be zero, and thus the calculation of `0 - 1` will result in accessing memory that is not meant to be read.
You could compare this to an "array index out of bounds" panic in Go.

You need to trace back why this `back()` is called in a case where the corresponding list is empty.
