### ISSUE TITLE
ConfigWindowsMoveFromTitleBarOnly available?

### ISSUE THREAD

**Issue by kpfaulkner** [inkyblackness/imgui-go#189]
I'm trying to make it so windows can only be moved via title bar... I *think* ConfigWindowsMoveFromTitleBarOnly is supposed to be configurable somewhere but I cannot see where. Is this enabled with imgui-go or on the todo list?

First time I've tinkered with imgui in general, but wow, loving this Go wrapper... makes some tool dev so much easier!!

**Comment by dertseha** [comment]
Hello there and thank you for your message.
This `ConfigWindowsMoveFromTitleBarOnly` option is on the `IO` type and currently not exposed by the Go wrapper.
You could extend the wrapper to provide a setter for this option.

However, I'd also like to point you towards https://github.com/AllenDang/cimgui-go , because thanks to that auto-generated wrapper, I'm about to sunset this wrapper here. If you are at the beginning of using imgui, I recommend rather using that wrapper.

**Comment by eliasdaler** [comment]
@dertseha, are you 100% sure about this? I need to check that wrapper out, but is it as good as imgui-go at least?

If you don't have enough time to maintain imgui-go, perhaps I can help with it.

**Comment by dertseha** [comment]
eliasdaler, I am not sure what you are referring to with "this"; Going through my comment, I say "all of it".
* Searching for `ConfigWindowsMoveFromTitleBarOnly` brings only results in C++ code, so, it is not exposed in the wrapper
* AllenDang/cimgui-go is auto-generated
* I have sunset this wrapper here
* I recommend using AllenDang/cimgui-go instead

As for the question "is it as good as this one here" this depends on the applied quality factors which may be different between us. For me, apart from the extra work effort, my realization is that the core **Dear ImGui** is an ever-moving target that makes it very difficult to maintain a Go-idiomatic version compatibility. I'd say that there is endless effort needed to keep this wrapper here up-to date over time, and I see a diminishing effort over time necessary to make an auto-generated wrapper "as good" as one would want.
This has been discussed in #162 and resulted in announcement #192 .

**Comment by eliasdaler** [comment]
I see, I can definitely understand how it feels, with me being a maintainer of ImGui-SFML and trying to catch up to other backends, while not even using SFML myself for the last several years.

Thanks to the links to discussions - I've missed them. In case I'll find it hard to migrate to cimgui-go, I can fork imgui-go and maintain it myself for a while, after all. But I'll definitely try to contribute to cimgui-go as well.

Thanks for your work!
