### ISSUE TITLE
Potentially out-of-date documentation

### ISSUE THREAD

**Issue by nhillery** [inkyblackness/imgui-go#40]
On page https://godoc.org/github.com/inkyblackness/imgui-go#pkg-files,
the phrase:
    "Refer to the _examples directory"

may refer to the directory structure before examples were moved to imgui-go-examples.

Cheers,
Nathan.

**Comment by dertseha** [comment]
Hello Nathan!
You are right - this one slipped through, thank you for the notification! I'll update the text.
