### ISSUE TITLE
Frame rate is ~x50 slower in comparison with native

### ISSUE THREAD

**Issue by ez-zrizi-info** [inkyblackness/imgui-go#41]
I'm turning off VSync on both scenarios and getting this huge performance gap -- is this mostly the result of the wrapper/[cgo overhead](https://about.sourcegraph.com/go/gophercon-2018-adventures-in-cgo-performance)?

**imgui-go example:**
![imgui-go](https://user-images.githubusercontent.com/38176498/58757393-7e850e00-8514-11e9-95c3-8f517b035d21.png)

**imgui example:**
![imgui](https://user-images.githubusercontent.com/38176498/58757396-85138580-8514-11e9-98c9-537e763200e5.png)

**Comment by dertseha** [comment]
Hello there and thank you for your message!
The Go example is throttled in terms of framerate, as I like to avoid running 100% load on CPU.
See the last line in the example Run.go: https://github.com/inkyblackness/imgui-go-examples/blob/master/internal/demo/Run.go#L102
```
// sleep to avoid 100% CPU usage for this demo
<-time.After(time.Millisecond * 25)
```
Comment this line, and it should be faster :)

**Comment by ez-zrizi-info** [comment]
Hey, wow there, blazing fast now. Impressive work on the wrapper, friend. Funny how I missed this one liner... Thanks very much for contributing this and thanks for the responsiveness.
