### ISSUE TITLE
Put two InputText in frame will cause weird issue.

### ISSUE THREAD

**Issue by AllenDang** [inkyblackness/imgui-go#43]
1. Put two InputText in frame.
2. Click the first one, it cannot get focus, cannot input anything.
3. Click the second one, it gains the focus, input something, two InputText will has same string I've entered.

Here is the sample code:

```
var str1 string
var str2 string
for !p.ShouldStop() {
    p.ProcessEvents()
    p.NewFrame()
    imgui.NewFrame()
    {
        imgui.Begin("Test")
        imgui.InputText("", &str1)
        imgui.InputText("", &str2)
        imgui.End()
    }
...
}
```

**Comment by dertseha** [comment]
Hello @AllenDang and thank you for your message!
You've come across not a bug, but rather a weird property of ImGui.

The first parameter of most controls is typically a "label". It acts as both as the text for visual display of the fields name, as well as the internal ID of the control.
If two (or more controls) have the same ID, then all sorts of strange behaviour comes out of it :)

If you use two different (non-empty) strings as the first parameter , then the two fields would behave as expected.

If your intention was to have two text fields without any visual name, then you can make use of some extra behaviour that ImGui has built in. The displayed text can be separate from the internal ID by using the separator `##` in the label text. So, for your case it would be 
```
imgui.InputText("##a", &str1)
imgui.InputText("##b", &str2)
```
that creates two separate text input fields without visual label, yet two different internal IDs.

To quote the `imgui.h` file:
>    // ID stack/scopes
>    // - Read the FAQ for more details about how ID are handled in dear imgui. If you are creating widgets in a loop you most
>    //   likely want to push a unique identifier (e.g. object pointer, loop index) to uniquely differentiate them.
>    // - You can also use the "Label##foobar" syntax within widget label to distinguish them from each others.
>    // - In this header file we use the "label"/"name" terminology to denote a string that will be displayed and used as an ID,
>    //   whereas "str_id" denote a string that is only used as an ID and not normally displayed.

Does this cover your issue?

**Comment by AllenDang** [comment]
@dertseha Thanks for your help!! It is solved.
