### ISSUE TITLE
Cannot paste text to InputText by Cmd+v.

### ISSUE THREAD

**Issue by AllenDang** [inkyblackness/imgui-go#44]
OS: MacOS 10.14.5

Platform: GLFW
Renderer:OpenGL3

Reproduce steps:
1. Copy text from some other app by Cmd+c
2. Click input text control
3. Cmd+v

Expected result:
The text has been pasted into input text.

Actual result:
No text is pasted.

If I entered some text into input text control, select them, Cmd+c or Cmd+x, then Cmd+v will paste selected text into the input text.

Looks like the app has it's own clipboard, and cannot share with OS?

**Comment by dertseha** [comment]
Hello again, @AllenDang !

This is because Dear ImGui implements a OS-clipboard binding only for MS windows. For other platforms, the clipboard has to be made accessible via functions on the IO data structure.

Currently, this has not been added to the wrapper.

I can't tell when I'll have some time to add it - would you be interested to do a pull request? It will need a little trickery with cgo and pointer handles I guess.

**Comment by AllenDang** [comment]
@dertseha Sure, can you point me a proper place to start? Like which part of the wrapper is related to it.

**Comment by dertseha** [comment]
Ah, OK.
I've written a guide what to look for when updating the ImGui version. And: I believe there's been quite a jump in functionality from 1.6x to 1.70, so please double-check that the API stays compatible.

**Comment by AllenDang** [comment]
@dertseha 
I updated imgui to 1.72b, rename SetNextTreeNodeOpen to SetNextItemOpen according to breaking change section of imgui.cpp.
Then I find InputText acting really weird, it will lose focus if I press key quick.
I guess something went wrong in the IO part.
Any thoughts where the problem might be?

**Comment by AllenDang** [comment]
Maybe there is another solution for it.
I noticed that glfw comes with clipboard support, and the demo of imgui_impl_glfw shows the code about how to connect them together.

```
static bool ImGui_ImplGlfw_Init(GLFWwindow* window, bool install_callbacks, GlfwClientApi client_api)
{
    ...
    io.SetClipboardTextFn = ImGui_ImplGlfw_SetClipboardText;
    io.GetClipboardTextFn = ImGui_ImplGlfw_GetClipboardText;
    ....
}

static const char* ImGui_ImplGlfw_GetClipboardText(void* user_data)
{
    return glfwGetClipboardString((GLFWwindow*)user_data);
}

static void ImGui_ImplGlfw_SetClipboardText(void* user_data, const char* text)
{
    glfwSetClipboardString((GLFWwindow*)user_data, text);
}
```

I'm not familiar with C++ which slow down the wrapping process...

**Comment by AllenDang** [comment]
Aha!!! I got it work!

I copied the MacOS clipboard implementation from imgui 1.72b, and make it work.

Yeah!!!

**Comment by dertseha** [comment]
heh, well, ok, this way you have a solution for your project, though I'd like to avoid a patchwork :)

The two function pointers that you found were the ones I was to referring to in my initial comment. It is possible to wrap this, though it requires some extra layer of indirection. I have a longer train ride coming up this week, perhaps I find some time to do this then.

As for an upgrade to 1.7x, I figured that it won't be easy - such an upgrade needs some extra love.

**Comment by AllenDang** [comment]
Great work! I merged this fix into my fork, it works like a charm!
I also learnt a lot from your solution. Thanks!

I'm trying to make this project a good solution for developing desktop app rather then embed UI in game, don't know what's your thoughts?

I kept looking for a solution to develop cross platform desktop UI so long. 

I figure imgui-go could be a handy solution for that.

So in my fork, I provide a MasterWindow to hide the platform and renderer detail, and expose some window operations, like GetSize, Maximize, SetResizable, etc...
And use GLFW and OpenGL3 as the default backend.

The usage of imgui-go now become very straight forward like below.

```
package main

import (
	"fmt"
	"image"
	_ "image/png"
	"os"

	"github.com/AllenDang/imgui-go"
)

var (
	inputText string
	counter   int
	imageId   imgui.TextureID
)

func initFunc(w *imgui.MasterWindow) {
	imgFile, err := os.Open("gopher.png")
	if err != nil {
		panic(err)
	}
	defer imgFile.Close()

	// Decode detexts the type of image as long as its image/<type> is imported
	img, _, err := image.Decode(imgFile)
	if err != nil {
		panic(err)
	}
	imageId, err = w.LoadImage(img)
	if err != nil {
		panic(err)
	}
}

func run(w *imgui.MasterWindow) {
	imgui.Begin("Simple test")

	imgui.Text("This is some useful text")

	imgui.InputText("Hello", &inputText)

	if imgui.Button("Button") {
		counter++
	}
	imgui.SameLine()
	imgui.Text(fmt.Sprintf("counter = %d", counter))

	imgui.Image(imageId, imgui.Vec2{X: 128, Y: 128})

	imgui.End()
}

func main() {
	w := imgui.NewMasterWindow("Simple test", 1280, 720, false, "SimSun.ttf", 13, [4]float32{0, 0, 0, 1})
	w.Main(initFunc, run)
}
```

**Comment by dertseha** [comment]
Great that it works! I'll release the lib in a new version soon - I now want to get the examples project work with it.

Apart from that, you should have a look at http://gioui.org . I saw its presentation at GopherCon UK a few weeks back and it has potential: It provides a UI app framework (roughly based on the immediate UI system), with cross-compilation tools for desktop, webassembly, Android, and iOS!

If you still want to create your own package, I recommend you give it a dedicated name, as it isn't "just" imgui-go anymore.

**Comment by AllenDang** [comment]
Sure, I will take a look at gioui.org first and get back to you.

**Comment by dertseha** [comment]
All right. imgui-go is released in v.1.10.0 - and the examples project in v1.1.0 - all available now.
Closing issue as per original post.
