### ISSUE TITLE
Load colorful png and render to gui turns to gray.

### ISSUE THREAD

**Issue by AllenDang** [inkyblackness/imgui-go#48]
Backend: GLFW/GL3

I created a function to load png as texture.

```
func (renderer *OpenGL3) createImageTexture(img *image.RGBA) (uint32, error) {
	// Upload texture to graphics system
	var lastTexture int32
	var handle uint32
	gl.GetIntegerv(gl.TEXTURE_BINDING_2D, &lastTexture)
	gl.GenTextures(1, &handle)
	gl.BindTexture(gl.TEXTURE_2D, handle)
	gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR) // minification filter
	gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR) // magnification filter
	gl.TexImage2D(gl.TEXTURE_2D, 0, gl.RGBA, int32(img.Bounds().Dx()), int32(img.Bounds().Dy()), 0, gl.RGBA, gl.UNSIGNED_BYTE, gl.Ptr(img.Pix))
	gl.GenerateMipmap(gl.TEXTURE_2D)

	// Restore state
	gl.BindTexture(gl.TEXTURE_2D, uint32(lastTexture))

	return handle, nil
}
```
Then I tried to load this

![gopher](https://user-images.githubusercontent.com/18550/64704412-d3a3c900-d4e0-11e9-9f70-9a032c22681a.png)

```
imgFile, err := os.Open("gopher.png")
if err != nil {
	panic(err)
}
defer imgFile.Close()

// Decode detexts the type of image as long as its image/<type> is imported
img, _, err := image.Decode(imgFile)
if err != nil {
	panic(err)
}

rect := img.Bounds()
rgba := image.NewRGBA(rect)
draw.Draw(rgba, rect, img, rect.Min, draw.Src)

imageID, err = w.LoadImage(rgba)
if err != nil {
	panic(err)
}

```

And display to gui by

`imgui.Image(imageID, imgui.Vec2{X: 128, Y: 128})`

Here is it, gray

![屏幕快照 2019-09-11 下午10 14 01](https://user-images.githubusercontent.com/18550/64704824-7ceabf00-d4e1-11e9-9751-cc54d281e5ab.png)

Any thoughts?

**Comment by Nicify** [comment]
You should check the "Out_Color" in your fragment shader source code.

**Comment by AllenDang** [comment]
@Nicify 
Oh my!!!! You just save my world!
I copied the fragmentShader from imgui's implementation and it just work!

**Comment by AllenDang** [comment]
@dertseha 
The fragment shader code of your demo's GL3 renderer should be changed to below to fix this.

```
uniform sampler2D Texture;
in vec2 Frag_UV;
in vec4 Frag_Color;
out vec4 Out_Color;
void main()
{
    Out_Color = Frag_Color * texture(Texture, Frag_UV.st);
}
```

**Comment by AllenDang** [comment]
@dertseha 
Sign.... you are right, it ruin the curves and fonts and background color...
I miss those last night because my eye-protection color tuning software...

I'll check your answer and try to fix it.
