### ISSUE TITLE
how to display unicode

### ISSUE THREAD

**Issue by coolit** [inkyblackness/imgui-go#6]
e.g. 
```
imgui.Text("ภาษาไทย测试조선말")
```

**Comment by coolit** [comment]
Is it possible to enable the usage like:
imgui.Text(u8"ภาษาไทย测试조선말")
Ref: 
ImGui::Text(u8"hello 菜单"); 
https://github.com/ocornut/imgui/issues/307

**Comment by dertseha** [comment]
Hello there and thank you for your message!
I wasn't able to cross-check it so far; imgui does support Unicode, though you have to load fonts with special parameters. It seems that one of the functions of Font.GetGlyphRanges* is needed to properly enable such character ranges (as also indicated by the mentioned issue - the main readme.md has also such an example).
These functions aren't exported so far in the wrapper. I might get to it in the upcoming days, or you could also give it a try to extend it :)

**Comment by coolit** [comment]
Sorry I am too new as a learner to make any contribution. It seems much memory will be needed for glyphs other than default one. And what if you need to show different languages at the same time? I mean, why imgui cannot display unicode characters like a native gui does?

**Comment by dertseha** [comment]
I will have a look at it during the upcoming days.
Multiple languages will probably require different fonts loaded up at the same time.
As to why imgui needs this special handling, I don't know - this is only something the original imgui maintainers can answer, sorry.

**Comment by coolit** [comment]
Cool, thanks.

**Comment by dertseha** [comment]
Heya, @coolit !
I've just committed an extension to expose the GlyphRanges type and functions. With that I could make imgui display the test string from above. `imgui.Text("ภาษาไทย测试조선말")`

Note that support is currently somewhat limited - I don't know your usecase so far. Currently only a single set of language ranges per font is possible. So, to display the above test string, three separate fonts are required to be loaded - and one text can only make use of one font at a time.

Meaning:
First, load up fonts (here using font files that came with Windows10):
```
fontAtlas := io.Fonts()
/*
	fontAtlas.AddFontFromFileTTFV("C:\\windows\\fonts\\malgun.ttf", 16, imgui.DefaultFontConfig,
		fontAtlas.GlyphRangesKorean())
*/
/*
	fontAtlas.AddFontFromFileTTFV("C:\\windows\\fonts\\msjh.ttc", 16, imgui.DefaultFontConfig,
		fontAtlas.GlyphRangesChinese())
*/
fontAtlas.AddFontFromFileTTFV("C:\\windows\\fonts\\leelawui.ttf", 16, imgui.DefaultFontConfig,
	fontAtlas.GlyphRangesThai())

image := fontAtlas.TextureDataAlpha8()
```
Then you can print a string using the current font. By default, the first font is the current font. You can switch fonts by using `imgui.PushFont()` and `imgui.PopFont()` - hence only one font at a time available per text output. (Hence the commented lines - I wanted to try out different languages, and also, startup times become considerably longer per extra font)

There are font files that have "all" unicode characters available, although then you run into the next limitation: The GlyphRanges type currently is only available via the FontAtlas and its default ranges (e.g. `FontAtlas.GlyphRangesThai()`). So, there is currently no way to "merge" two or more font ranges (e.g. Thai and Chinese).
This would require a separate "builder" type and resource management by the user.
Yet, before implementing something that might not be necessary, I'd first want to have you test your usecase :)

Tell me if it works for you, and if that's the case, then I'll make another release.

**Comment by coolit** [comment]
Thanks for the quick response. 

My use case is to, show all unicode characters, esp. for natural language processing purposes, which means multiple or at least two languages needed to be shown at the same time.

Below is the result:
- Startup times become considerably longer, for Chinese and Korean, but not for Thai. This is acceptable for bigger programs, but not good for smaller ones. I have tried imgui-rs, its start time was always 2-3 seconds, which seemed no different in default font mode from other font modes. 
- Fonts become very unclear. 
- I have no idea how to push and pop font properly.  The following code will lead to program exit.
`
if imgui.Button("Button") {
	io := imgui.CurrentIO()
	fontAtlas := io.Fonts()
	imgui.PushFont(fontAtlas.AddFontFromFileTTFV("C:\\windows\\fonts\\leelawui.ttf", 16, imgui.DefaultFontConfig,fontAtlas.GlyphRangesThai()))
}
`

**Comment by dertseha** [comment]
I'd say the longer load times come from rendering all the various characters into the font texture. 
As for fonts becoming unclear, this might have something to do with selected font, size, and possible also with (pixelated) scaling on HiDPI displays.
Please keep in mind, the wrapper itself does not add any logic on its own.

The fonts have to be added before you retrieve the font texture - i.e. before calling fontAtlas.TextureDataAlpha8() - typically during setup. The AddFontFromFile() functions return the font object that you can then use.
So, during setup, add all the fonts and language ranges you need, and keep the respective returned font references. Then, when rendering call `imgui.PushFont(fontA) imgui.Text("...") imgui.PopFont()`.

You write "multiple languages needed to be shown at the same time" - is that in the same string (as in `imgui.Text(<text containing both thai and chinese>)` or do you know beforehand which language it will be? If texts are separated by language, then the Push/Pop approach should be fine.

**Comment by coolit** [comment]
I tested again.
01- I used the same font, and machine. But in imgui-rs, the start time is around 2 seconds, compared with around 9.5 seconds in imgui-go. As for font clarity, please see the attached picture. So I was just wondering, may there is something can be learned from imgui-rs to make imgui-go start faster and show more clearly.
![011](https://user-images.githubusercontent.com/13397709/45914401-5e765880-be77-11e8-889b-7c6b116eaba6.jpg)
02- Now it works fine, thanks.
03- Yes, I can know beforehand, but sometimes they are mixed together in a sentence. When any character other than the specified one has been detected, a font including all Unicode characters can be pushed, if the above mentioned builder is available.

**Comment by dertseha** [comment]
Ok, great - thank you for cross testing.
As for performance, figuring that out may take a while. I have no knowledge about Rust, though perhaps I can cross-test with the C++ variant. It could be something about compiler/optimization settings perhaps. (rough idea).

Regarding the quality, this now has a hint of similarity with #5 . I am now thinking about perhaps there's a difference in how OpenGL/textures are handled in the demos - again a rough guess.

I can add a builder to merge glyph ranges, though that may take a few days again until I get to some coding again.

**Comment by coolit** [comment]
Please take your time, there is no hurry. But if without those extra font, imgui-go is much faster in start time. Thank you for your great efforts.

**Comment by dertseha** [comment]
@coolit I've added a `GlyphRangesBuilder` that creates `AllocatedGlyphRanges` instances.
Do you have a combined font to test it with?

**Comment by coolit** [comment]
Hello there, sorry to be late. I do have a combined font, but the problem is I am too entry level to figure out how to make it work.  So attached please find the file for your reference, which combined Korean with Chinese.
[lihei.zip](https://github.com/inkyblackness/imgui-go/files/2442076/lihei.zip)

**Comment by dertseha** [comment]
Thank you for the example font, this helped. I had to extend the wrapper a bit to properly support such large font textures.

Here's an example code to use it:
```
	var builder imgui.GlyphRangesBuilder
	builder.AddExisting(fontAtlas.GlyphRangesDefault())
	builder.AddExisting(fontAtlas.GlyphRangesKorean())
	builder.AddExisting(fontAtlas.GlyphRangesChinese())
	ranges := builder.Build()
	fontAtlas.AddFontFromFileTTFV("lihei.ttf", 16, imgui.DefaultFontConfig, ranges.GlyphRanges)
	fontAtlas.SetTexDesiredWidth(8192)
	image := fontAtlas.TextureDataAlpha8()
```
The `ranges` variable should be kept. At the end of the program, when imgui has been shut down, call `ranges.Free()` in order to free the corresponding allocated resources.

You also see the new `FontAtlas.SetTexDesiredWidth()` function which was necessary. By default, the two font sets require a texture of 4096x32768, which OpenGL rejected for me.

Apart from that, I figured out that the function call to `FontAtlas.Build()` is taking so long (calling down to the stb_truetype library). I have no idea why this one would be slower than a native build; The only hunch I have is perhaps a difference between mingw and msvc compilers.

Please have a try - if it works for you, I'll make a new release :)

**Comment by coolit** [comment]
Great job. It worked very well. It is much more clear with this font.  Imgui-go takes less than half of memory taken by imgui-rust. Just the start time is kind of long.

**Comment by dertseha** [comment]
As per original issue, capability of displaying non-default unicode characters, this has been solved and is released in [v1.2.0](https://github.com/inkyblackness/imgui-go/releases/tag/v1.2.0). Hence I'm closing this issue.

For the start time, I've created #7 , because currently I have no idea where this is coming from and would be a blocker otherwise.
Simlar to the clarity, I suspect similarities to #5 and want to direct focus to there. Just to be clear, are you running on MS Windows, or macOS - and do you have a HiDPI display (i.e., what is you resolution)?

**Comment by dertseha** [comment]
Addendum: The clarity issue seems to have been found - see [here](https://github.com/inkyblackness/imgui-go/issues/5#issuecomment-427304266).

**Comment by Gildin** [comment]
...
