### ISSUE TITLE
Selectable doesn't work.

### ISSUE THREAD

**Issue by AllenDang** [inkyblackness/imgui-go#63]
Selectable should behave like a toggle, but I cannot get it work. 

```
var selected bool
func loop(..) {
  selected = imgui.SelectableV("Selectable", selected, 0, imgui.Vec2{})
  fmt.Println(selected)
}
```
From log I can see that when mouse down, selected is True, mouse up, selected is False again.
This makes it would never to selected.

**Comment by AllenDang** [comment]
I see, it seems is designed to work with combo by default.

**Comment by AllenDang** [comment]
I met a problem about how to get the BeginCombo works with selectable...

```
        imgui.BeginCombo(c.label, c.previewValue)
	for i, item := range c.items {
		if imgui.Selectable(item) {
			fmt.Println(item)
		}
	}

	imgui.EndCombo()
```
I put it between imgui.Begin and imgui.End, and error occurred.

```
panic: Assertion failed!
File: imgui.cpp, Line 7549

Expression: window->Flags & ImGuiWindowFlags_Popup
```

**Comment by dertseha** [comment]
@AllenDang For completeness: Selectable() is not exclusive to combo boxes. See demo window -> Widgets -> Selectables -> Basic .

The return value of such functions is like an event. The intention is to return true only "once", during which some business logic is performed. In other words, the return value indicates "I have been selected during this iteration", not "I am currently in the selected state".
