### ISSUE TITLE
Load GlyphRangesChineseFull takes nearly 6 seconds, way too slow...

### ISSUE THREAD

**Issue by AllenDang** [inkyblackness/imgui-go#68]
Hi, @dertseha 

I'm working on a app which needs to display content of web pages crawled by crawlers.
Currently the biggest issue is load GlyphRangesChineseFull takes nearly 6 seconds, and there still lots of chinese characters are not included.

I read the documents of imgui and found out GlyphRangesBuilder might be the solution. I could calculate all the characters need to be displayed and create GlyphRanges for them before rendering.

So I tried below solution.
```
                 fonts := Context.IO().Fonts()

		ranges := imgui.NewGlyphRanges()
		builder := imgui.NewFontGlyphRangesBuilder()

		// Compose all the strings need to be displayed
		var runes []rune
		for k := range fs.charMap {
			runes = append(runes, k)
		}

		builder.AddText(string(runes))
		builder.BuildRanges(ranges)

		fonts.AddFontFromFileTTFV(fs.fontPath, fs.fontSize, imgui.DefaultFontConfig, ranges.Data())
		alpha8 := fonts.TextureDataAlpha8()
		textureId, _ := Context.renderer.LoadAlpha8(alpha8)
		fonts.SetTextureID(textureId)
```

Here is the renderer side code
```
func (renderer *OpenGL3) LoadAlpha8(img *Alpha8Image) (TextureID, error) {
	// Upload texture to graphics system
	var lastTexture int32
	var handle uint32
	gl.GetIntegerv(gl.TEXTURE_BINDING_2D, &lastTexture)
	gl.GenTextures(1, &handle)
	gl.BindTexture(gl.TEXTURE_2D, handle)
	gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR) // minification filter
	gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR) // magnification filter
	gl.TexImage2D(gl.TEXTURE_2D, 0, gl.RGBA, int32(img.Width), int32(img.Height), 0, gl.ALPHA, gl.UNSIGNED_BYTE, gl.Ptr((*C.uint)(img.Pixels)))
	gl.GenerateMipmap(gl.TEXTURE_2D)

	// Restore state
	gl.BindTexture(gl.TEXTURE_2D, uint32(lastTexture))

	// Add Image Type to last 8 bit of the texture id to use different shader to render bitmap correctly.
	textureId := TextureID(handle)
	imageType := TextureID(1)

	textureId |= imageType << 56
	return textureId, nil
}
```
But all the characters displayed as black squares.
I'm I doing things right?

**Comment by AllenDang** [comment]
I followed your recent check about FreeType staff, found out a demo code in imgui/misc/freetyp.h, and also found out there already a method in RendererOpenGL3 in your demo project to createFontTexture.

I finally got some progress, but still didn't make the whole thing works as expected.

Here is what I got right now.

I created a function to create FontAtlas according to pass in string

```
func (fs *FontStash) Rebuild() bool {
	if fs.needRebuild {
		fonts := Context.IO().Fonts()

		ranges := imgui.NewGlyphRanges()
		builder := imgui.NewFontGlyphRangesBuilder()

		// Compose all the strings need to be displayed
		if len(fs.charMap) > 0 {
			var runes []rune
			for k := range fs.charMap {
				runes = append(runes, k)
			}

			builder.AddText(string(runes))
		} else {
			builder.AddRanges(fonts.GlyphRangesDefault())
		}

		builder.BuildRanges(ranges)

		fonts.AddFontFromFileTTFV(fs.fontPath, fs.fontSize, imgui.DefaultFontConfig, ranges.Data())

		fs.needRebuild = false
		return true
	}
	return false
}
```

And in the GLFW window's main loop, invoke the Rebuild method if any new string is added.
```
// If font stash is set, build it now
if Context.fontStash != nil && Context.fontStash.Rebuild() {
	w.renderer.Dispose()
	w.renderer.CreateDeviceObjects()
}

p.NewFrame()
imgui.NewFrame()

w.updateFunc(w)

imgui.Render()

r.PreRender(w.clearColor)
r.Render(p.DisplaySize(), p.FramebufferSize(), imgui.RenderedDrawData())
p.PostRender()
```

Sadly it still doesn't work...

**Comment by dertseha** [comment]
To clarify - when you use `GlyphRangesChineseFull()`, albeit taking some time to compile, are the characters you are missing displayed?

If not, then I'd suspect either the characters are missing in the full range of **Dear ImGui** (unlikely), or the given font does not have them (possible). Do you have a way to figure out if the runes that you are missing can indeed be displayed by the font you are using?

Also, going back a few steps: Have you verified the whole render sequence works with standard latin characters? If they are also displayed as black squares, then the render sequence has something.

**Comment by AllenDang** [comment]
@dertseha 
Yes, the GlyphRangesChineseFull is incomplete and the font I'm using indeed include the missing runes.

The default latin characters are fine and most of the chinese runes works fine also.

I can add the missing glyphranges manually, just the start up time is way too slow...

**Comment by AllenDang** [comment]
@dertseha Thanks for your kindly help. I'll check the freetype and try to make a build for MacOS.

**Comment by AllenDang** [comment]
@dertseha MacOS could build without any change of the linux version of FreeTypeEnable.
One more question, how can I static link freetype?

**Comment by dertseha** [comment]
I suspect static linking should be possible by some `cgo` directives in one of your files.
Though, I'm not sure whether this would work for used libraries. This you'll have to test.
