### ISSUE TITLE
Creating non-default font texture takes much longer than in native build

### ISSUE THREAD

**Issue by dertseha** [inkyblackness/imgui-go#7]
Found through #6, the function call of `FontAtlas.Build()` (through call such as `FontAtlas.GetTexDataAsAlpha8()` takes considerably longer (several seconds) than the native build when using non-default unicode fonts, such as Chinese ones.

From a cursory investigation I'm quite puzzled as to why this happens.
The only hunch that I have so far is a difference in compiler optimization, as this one so far has been found under Windows, where MSVC (native) and mingw (go) are in use. To cross verify, a Chinese font needs to be cross-tested under Linux.
Other than that, perhaps there are other `#define`s in play between the native and Go variants.

**Comment by coolit** [comment]
I am running on Windows 10 64x laptop, with 1920*1080 resolution.

**Comment by dertseha** [comment]
I dug deeper and took some crude performance metrics.
It comes down to the stb_truetype function `stbtt_PackFontRangesRenderIntoRects()` (Called from `ImGui::ImFontAtlasBuildWithStbTruetype()`, called from `ImGui::ImFontAtlas::Build()`). Of the big loop in that function, the call to `stbtt_MakeGlyphBitmapSubpixel()` takes the most time.
While the native variant takes a noticeable time in there for a Chinese font, the Go variant needs about 5 times of that duration (1.2s -> 6s).

I even tried to add compiler flags to the CGO call (`-O2` and `-O3`), though this had no effect.

So, we're deep in STB code and I have no idea why this is happening or what to do against this.
I'll be happy if anyone comes up with an explanation or possibly a solution, so it is marked with `help wanted` - though, for the time being I also have to accept it as-is and mark it with `wontfix`.

**Comment by SemMulder** [comment]
I currently have FreeType support working here: https://github.com/SemMulder/imgui-go (along with some other stuff), I will open a PR soon. FreeType might rasterize these fonts faster?

**Comment by dertseha** [comment]
Interesting - thank you for investigating this.
Are different build tags in play? Because I wonder how the same library compiled natively with its example uses a different font renderer.

**Comment by SemMulder** [comment]
> Are different build tags in play?

Nope. It just links FreeType if (and only if) you use FreeType to build the FontAtlas. This leaves it up to the user to link FreeType dynamically or statically by providing a corresponding `PKG_CONFIG_PATH`. It's worth mentioning that that means that by default it will link with the system FreeType. The API is equivalent to the one used in the C version: https://github.com/ocornut/imgui/tree/master/misc/freetype.

I'm currently working on an open source project that uses this and links FreeType statically. I'll link that project here once it is in a cleaner state ;).

**Comment by SemMulder** [comment]
I opened a PR here: https://github.com/inkyblackness/imgui-go/pull/58.

**Comment by dertseha** [comment]
@SemMulder thank you for the work on FreeType.
Sadly, this doesn't "automatically" build on MS Windows. I only have basic mingw compiler installation, and no pkg-config for example.
a) Is there a way to enable this by explicit tags?
b) Alternatively, what would be the requirements (setup procedure) for building this on MS Windows? If you have this at hand, then great, this could be added to the readme. Otherwise, I'd have to investigate myself anyway :) The whole thing is currently in branch "[feature/58-add-freetype](https://github.com/inkyblackness/imgui-go/tree/feature/58-add-freetype)"

**Comment by SemMulder** [comment]
The way I did it was to build FreeType as part of the build process of the final project and link that statically. You can find that here: https://developer.blender.org/source/blender-open-data/browse/features%252Fnew_website/. The relevant parts are in the `launcher/Makefile` and `launcher/freetype2/Makefile` files. However, for a library it might be more idiomatic to vendorise the code and build it using cgo?

**Comment by dertseha** [comment]
It should still be an option to include this for the end-user. The wrapper should not become a combination of various things. Furthermore I'd like to have the `imgui-go` package to work with plain go commands out of the box and not require a build structure around it.

Currently I'm attempting to solve this via build-tags and a sub-package. This approach appears promising, though I have to sort out a few details.

**Comment by dertseha** [comment]
Thanks to @SemMulder , using [v2.0.0](https://github.com/inkyblackness/imgui-go/releases/tag/v2.0.0) and the FreeType support should help here.

Not having FreeType in a specific build environment is a separate issue.

**Comment by AllenDang** [comment]
@SemMulder Can you share about how to link FreeType statically?

**Comment by SemMulder** [comment]
@AllenDang You need to compile FreeType as a static library and prepend the corresponding `.pc` file to `PKG_CONFIG_PATH`.

For compiling FreeType see `Makefile` and `modules.cfg` here:
https://developer.blender.org/source/blender-open-data/browse/master/launcher/freetype2/;6f6e8acdd37527721c91e8bf01aa258678a4ab8c

For prepending to the `PKG_CONFIG_PATH` see the following `Makefile`:
https://developer.blender.org/source/blender-open-data/browse/master/launcher/Makefile;6f6e8acdd37527721c91e8bf01aa258678a4ab8c

Note that this is not yet using imgui-go v2.0.0, but I believe this approach should work.

**Comment by AllenDang** [comment]
@SemMulder Thanks very much!
