### ISSUE TITLE
IsWindowFocused()

### ISSUE THREAD

**Issue by JetSetIlly** [inkyblackness/imgui-go#76]
iggIsWindowFocused() in imguiWrapper.cpp (line 584) is incorrectly calling IsWindowHovered()

   >IggBool iggIsWindowFocused(int flags)
   >{
   >    return ImGui::IsWindowHovered(flags) ? 1 : 0;
   >}

**Comment by dertseha** [comment]
Hey, @JetSetIlly - thank you for noticing!
This has been fixed and [v2.1.1](https://github.com/inkyblackness/imgui-go/releases/tag/v2.1.1) was released just now.
