### ISSUE TITLE
InsertBytes() null pointer dereference

### ISSUE THREAD

**Issue by JetSetIlly** [inkyblackness/imgui-go#78]
Calling `InsertBytes()` with bytes argument of length zero can panic the program.

The call to `C.iggInputTextCallbackDataInsertBytes()` should be inside the `byteCount > 0` block.

```func (data InputTextCallbackData) InsertBytes(offset int, bytes []byte) {
	if (offset < 0) || (offset > data.bufTextLen()) {
		panic("invalid offset")
	}
	var bytesPtr *C.char
	byteCount := len(bytes)
	if byteCount > 0 {
		bytesPtr = (*C.char)(unsafe.Pointer(&bytes[0]))
		C.iggInputTextCallbackDataInsertBytes(data.handle, C.int(offset), bytesPtr, C.int(byteCount))
	}
}
```

**Comment by dertseha** [comment]
Interesting - good find!
It feels like I had some reason to leave it outside, yet this doesn't work.
Thank you for noticing!

**Comment by dertseha** [comment]
Handled by pull request.
