### ISSUE TITLE
NULL instead of nullptr when running on El Capitan

### ISSUE THREAD

**Issue by peterhellberg** [inkyblackness/imgui-go#8]
I just downloaded this package to try it out, but had to make this change to [WrapperConverter.h](https://github.com/inkyblackness/imgui-go/blob/master/WrapperConverter.h) in order for it to compile under El Capitan (`10.11.6`) and `go version go1.11.1 darwin/amd64`

```diff
diff --git a/WrapperConverter.h b/WrapperConverter.h
index c4a09c2..ff6f14b 100644
--- a/WrapperConverter.h
+++ b/WrapperConverter.h
@@ -14,9 +14,9 @@ class TypeWrapper
 {
 public:
    TypeWrapper(IggType *iggValue)
-      :  iggValue(iggValue), imguiValue(nullptr)
+      :  iggValue(iggValue), imguiValue(NULL)
    {
-      if (iggValue != nullptr)
+      if (iggValue != NULL)
       {
          imguiValue = &imguiBuffer;
          importValue(*imguiValue, *iggValue);
@@ -24,9 +24,9 @@ public:
    }
 
    TypeWrapper(IggType const *constIggValue)
-      :  iggValue(nullptr), imguiValue(nullptr)
+      :  iggValue(NULL), imguiValue(NULL)
    {
-      if (constIggValue != nullptr)
+      if (constIggValue != NULL)
       {
          imguiValue = &imguiBuffer;
          importValue(*imguiValue, *constIggValue);
@@ -35,7 +35,7 @@ public:
 
    ~TypeWrapper()
    {
-      if (iggValue != nullptr)
+      if (iggValue != NULL)
       {
          exportValue(*iggValue, *imguiValue);
       }
```

**Comment by dertseha** [comment]
Thank you for your message!
Seems like the proper flag for C++11 support is missing then, interesting.

**Comment by peterhellberg** [comment]
Yes, maybe solved by `CGO_CXXFLAGS="-std=c++11" go build` (I'm not at that computer right now)

**Comment by peterhellberg** [comment]
This issue does **not** seem to be present under macOS High Sierra (10.13.6) and `go version go1.11.1 darwin/amd64`

**Comment by dertseha** [comment]
Seems like the default language level was changed between these versions.
I'll add a compiler flag, might take a few days though at the moment.
Thank you again for testing it out!

**Comment by dertseha** [comment]
I've added the compiler flag as cgo comment.
May I ask you to retry with master/HEAD?

**Comment by peterhellberg** [comment]
Now it works as it should under El Capitan 👍
