### ISSUE TITLE
FreeType support under Windows using MinGW

### ISSUE THREAD

**Issue by neclepsio** [inkyblackness/imgui-go#91]
To get it working under Windows, using a properly setup MinGW environment (a port of GNU development environment), I simply deleted the `_linux` tag fom the name of `FreeTypeEnabled_linux.go`.

Everything works as expected. Please add a tag we can use for any linux-like build environment.

**Comment by dertseha** [comment]
Hello there and thank you for the message - and thank you for your patience!
Ah, good idea. In order to keep things compatible, I'll add an OR build tag - it's either Linux or gcc-compatible (or something experssive). I'll have a look.

**Comment by dertseha** [comment]
I removed the `_linux` suffix. If there are other environments that need yet another setup, these can receive dedicated handling then.
