### ISSUE TITLE
io.MouseDrawCursor 

### ISSUE THREAD

**Issue by neclepsio** [inkyblackness/imgui-go#92]
`io.MouseDrawCursor` is cited in [doc](https://pkg.go.dev/github.com/inkyblackness/imgui-go/v2?tab=doc#MouseCursor), but there is no way to set it.

**Comment by dertseha** [comment]
Good point. For the most part, documentation is copied from the original where possible.
In case that refers to an API that wasn't wrapped yet, this would be a dead end. There are probably more such cases.

**Comment by ptxmac** [comment]
Just made a PR to address this: https://github.com/inkyblackness/imgui-go/pull/147

**Comment by dertseha** [comment]
Thank you!
