### ISSUE TITLE
Version 1.76

### ISSUE THREAD

**Issue by neclepsio** [inkyblackness/imgui-go#93]
Version 1.76 is out, please consider update your great wrapper. Thank you.

**Comment by dertseha** [comment]
Thank you for the notice.
While I am happy to work on pull requests, this wrapper project is low on my list of priorities. 
If you want to give it a try, there's a guide in [CONTRIBUTING.md](https://github.com/inkyblackness/imgui-go/blob/master/CONTRIBUTING.md#upgrade-to-newer-dear-imgui-version) .
